name: Test PHP

on: [pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Composer Access
      run: composer config -g github-oauth.github.com ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Validate code against PSR2
      run: ./vendor/bin/phpcs ./ --extensions=php --standard=PSR2 --ignore=vendor/
